### ISSUE TITLE
Feelings arent functional on creation of a new Database

### ISSUE THREAD

**Issue by MattTheDev** [smcvey/tcz#1]
Output of Available Commands

TCZ> @feelings
 Abandoned          Adaptable          Adventurous        Affectionate       Aggressive
 Alert              Alive              Alone              Amazed             Amused
 Angelic            Angry              Annoyed            Anxious            Artistic
 Aroused            Attractive         Awesome            Bad                Batty
 Beastly            Beautiful          Belittled          Benevolent         Betrayed
 Bewildered         Blond              Blonde             Bloodthirsty       Blue
 Bold               Bored              Bouncy             Braindead          Brave
 Bright             Burnt              Calm               Catty              Chatty
 Cheerful           Chipper            Chirpy             Chuffed            Clever
 Clueless           Cocky              Cold               Colourful          Compassionate
 Confident          Confused           Considerate        Conspiratorial     Cool
 Corrupted          Crap               Crazy              Creative           Criticised
 Curious            Daft               Daring             Dead               Deceptive
 Delicious          Demonic            Depressed          Destroyed          Devious
 Disappointed       Disgruntled        Distorted          Distracted         Ditsy

---

On typing of the commands above:

TCZ> curious
Unknown command 'curious', Matt.  (Type HELP for help!)

Done on both root and newly created character.

Will dig into logs to see if I can find any supporting rhyme / reason.

**Comment by smcvey** [comment]
It's @feeling me = Curious

**Comment by MattTheDev** [comment]
Ugh... I meant the emotes.. ie: Smile, lol, etc.

help feelings brings up the list.
None of these function. 

 *42         ahem       alien      aliens     angst      baa       *band
  banner     bawl      *bearhug   *beavis     beg        belch     *bird
 *bite      *blame      blush      bnb       *bop        bounce    bow
  brb       *bud       *bud2      *buggie     buggs      burp     *butthead
 *butthead2 *cereal     cheer      chuckle    clap      *comfort  *congrats
  cough      cry       *cuddle     curse      curtsy     dudesay   daze
  dive       doh       *drool     *duck       dump       eek       elmer
 *eyes       fabio      faint      fart       fcount     fdl       ferkle
  fgender    flip      *flowers    fortune   *frenchy    frown    *garsh
  giggle     goofy      grin      *grind     *griz       groan    *grope
  grouphug  *grovel     grunt     *head      *hi5       *hold     *holds
 *hug       *hugg      *huggle    *jimmyhill  jump      *kiss      laff
  lag        lagg       laugh     *lick       lol       meep      *melvin
 *mentos    *misc       mistake    mlag      *moose     mope       mosh
 *newyear   *nibble     nod       *noodle    *noogie   *nudge      nuke
 *nurse     *pick      *pinch     *point     *poke      pose

I assume these are soft coded?

**Comment by smcvey** [comment]
Yeah they are.  There's evidence of a hard-coded feelings system that JC started, but never finished.  Not sure where to go with it.

**Comment by MattTheDev** [comment]
Alright cool - Ill strip out / block that help command and implement something softcoded! Thanks - closing this issue.
